kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node
spec:
  template:
    spec:
      containers:
        - name: gce-pd-driver
          image: PROW_GCEPD_IMAGE:latest
        - name: csi-driver-registrar
<<<<<<< HEAD
          image: gcr.io/gke-release/csi-driver-registrar:v1.0.1-gke.0
=======
          image: gcr.io/gke-release/csi-driver-registrar:v1.0.0-gke.0
>>>>>>> bc90fab... Update Prow Head Template
